name: Lint, Check Types, Test, Run Program
on: push

jobs:
  lint-and-check-types:
    name: Lint, Check Types, Test, Run Program
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - run: yarn eslint . --max-warnings 0
      - run: yarn tsc
      - run: npm test
      - run: node index.js sortBySubscriptionDate
